/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentIndexRouteImport } from './routes/student/index'
import { Route as RegistryIndexRouteImport } from './routes/registry/index'
import { Route as InstructorIndexRouteImport } from './routes/instructor/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as StudentProfileRouteImport } from './routes/student/profile'
import { Route as StudentMyRequestsRouteImport } from './routes/student/my-requests'
import { Route as StudentMyGradesRouteImport } from './routes/student/my-grades'
import { Route as StudentMyEnrollmentsRouteImport } from './routes/student/my-enrollments'
import { Route as StudentEnrollmentRouteImport } from './routes/student/enrollment'
import { Route as StudentCreateRequestRouteImport } from './routes/student/create-request'
import { Route as StudentAvailableCoursesRouteImport } from './routes/student/available-courses'
import { Route as StudentAcademicHistoryRouteImport } from './routes/student/academic-history'
import { Route as InstructorRecordGradesRouteImport } from './routes/instructor/record-grades'
import { Route as InstructorProfileRouteImport } from './routes/instructor/profile'
import { Route as InstructorMyRequestsRouteImport } from './routes/instructor/my-requests'
import { Route as InstructorMyCoursesRouteImport } from './routes/instructor/my-courses'
import { Route as InstructorGradeHistoryRouteImport } from './routes/instructor/grade-history'
import { Route as InstructorCreateRequestRouteImport } from './routes/instructor/create-request'
import { Route as InstructorCourseDetailRouteImport } from './routes/instructor/course-detail'
import { Route as InstructorClassRosterRouteImport } from './routes/instructor/class-roster'
import { Route as ErrorsOfflineRouteImport } from './routes/errors/offline'
import { Route as Errors404RouteImport } from './routes/errors/404'
import { Route as AuthLogoutRouteImport } from './routes/auth/logout'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AdminPeriodsRouteImport } from './routes/admin/periods'
import { Route as AdminLogsRouteImport } from './routes/admin/logs'
import { Route as AdminFacultiesRouteImport } from './routes/admin/faculties'
import { Route as AdminCoursesRouteImport } from './routes/admin/courses'
import { Route as AdminConfigRouteImport } from './routes/admin/config'
import { Route as AdminCampusesRouteImport } from './routes/admin/campuses'
import { Route as AdminAccountsIndexRouteImport } from './routes/admin/accounts/index'
import { Route as AdminAccountsRolesRouteImport } from './routes/admin/accounts/roles'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/student/',
  path: '/student/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistryIndexRoute = RegistryIndexRouteImport.update({
  id: '/registry/',
  path: '/registry/',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorIndexRoute = InstructorIndexRouteImport.update({
  id: '/instructor/',
  path: '/instructor/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/student/profile',
  path: '/student/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentMyRequestsRoute = StudentMyRequestsRouteImport.update({
  id: '/student/my-requests',
  path: '/student/my-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentMyGradesRoute = StudentMyGradesRouteImport.update({
  id: '/student/my-grades',
  path: '/student/my-grades',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentMyEnrollmentsRoute = StudentMyEnrollmentsRouteImport.update({
  id: '/student/my-enrollments',
  path: '/student/my-enrollments',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentEnrollmentRoute = StudentEnrollmentRouteImport.update({
  id: '/student/enrollment',
  path: '/student/enrollment',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentCreateRequestRoute = StudentCreateRequestRouteImport.update({
  id: '/student/create-request',
  path: '/student/create-request',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentAvailableCoursesRoute = StudentAvailableCoursesRouteImport.update({
  id: '/student/available-courses',
  path: '/student/available-courses',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentAcademicHistoryRoute = StudentAcademicHistoryRouteImport.update({
  id: '/student/academic-history',
  path: '/student/academic-history',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorRecordGradesRoute = InstructorRecordGradesRouteImport.update({
  id: '/instructor/record-grades',
  path: '/instructor/record-grades',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorProfileRoute = InstructorProfileRouteImport.update({
  id: '/instructor/profile',
  path: '/instructor/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorMyRequestsRoute = InstructorMyRequestsRouteImport.update({
  id: '/instructor/my-requests',
  path: '/instructor/my-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorMyCoursesRoute = InstructorMyCoursesRouteImport.update({
  id: '/instructor/my-courses',
  path: '/instructor/my-courses',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorGradeHistoryRoute = InstructorGradeHistoryRouteImport.update({
  id: '/instructor/grade-history',
  path: '/instructor/grade-history',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorCreateRequestRoute = InstructorCreateRequestRouteImport.update({
  id: '/instructor/create-request',
  path: '/instructor/create-request',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorCourseDetailRoute = InstructorCourseDetailRouteImport.update({
  id: '/instructor/course-detail',
  path: '/instructor/course-detail',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorClassRosterRoute = InstructorClassRosterRouteImport.update({
  id: '/instructor/class-roster',
  path: '/instructor/class-roster',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorsOfflineRoute = ErrorsOfflineRouteImport.update({
  id: '/errors/offline',
  path: '/errors/offline',
  getParentRoute: () => rootRouteImport,
} as any)
const Errors404Route = Errors404RouteImport.update({
  id: '/errors/404',
  path: '/errors/404',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLogoutRoute = AuthLogoutRouteImport.update({
  id: '/auth/logout',
  path: '/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPeriodsRoute = AdminPeriodsRouteImport.update({
  id: '/admin/periods',
  path: '/admin/periods',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/admin/logs',
  path: '/admin/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFacultiesRoute = AdminFacultiesRouteImport.update({
  id: '/admin/faculties',
  path: '/admin/faculties',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCoursesRoute = AdminCoursesRouteImport.update({
  id: '/admin/courses',
  path: '/admin/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConfigRoute = AdminConfigRouteImport.update({
  id: '/admin/config',
  path: '/admin/config',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCampusesRoute = AdminCampusesRouteImport.update({
  id: '/admin/campuses',
  path: '/admin/campuses',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAccountsIndexRoute = AdminAccountsIndexRouteImport.update({
  id: '/admin/accounts/',
  path: '/admin/accounts/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAccountsRolesRoute = AdminAccountsRolesRouteImport.update({
  id: '/admin/accounts/roles',
  path: '/admin/accounts/roles',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/campuses': typeof AdminCampusesRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/faculties': typeof AdminFacultiesRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/periods': typeof AdminPeriodsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/errors/404': typeof Errors404Route
  '/errors/offline': typeof ErrorsOfflineRoute
  '/instructor/class-roster': typeof InstructorClassRosterRoute
  '/instructor/course-detail': typeof InstructorCourseDetailRoute
  '/instructor/create-request': typeof InstructorCreateRequestRoute
  '/instructor/grade-history': typeof InstructorGradeHistoryRoute
  '/instructor/my-courses': typeof InstructorMyCoursesRoute
  '/instructor/my-requests': typeof InstructorMyRequestsRoute
  '/instructor/profile': typeof InstructorProfileRoute
  '/instructor/record-grades': typeof InstructorRecordGradesRoute
  '/student/academic-history': typeof StudentAcademicHistoryRoute
  '/student/available-courses': typeof StudentAvailableCoursesRoute
  '/student/create-request': typeof StudentCreateRequestRoute
  '/student/enrollment': typeof StudentEnrollmentRoute
  '/student/my-enrollments': typeof StudentMyEnrollmentsRoute
  '/student/my-grades': typeof StudentMyGradesRoute
  '/student/my-requests': typeof StudentMyRequestsRoute
  '/student/profile': typeof StudentProfileRoute
  '/admin': typeof AdminIndexRoute
  '/instructor': typeof InstructorIndexRoute
  '/registry': typeof RegistryIndexRoute
  '/student': typeof StudentIndexRoute
  '/admin/accounts/roles': typeof AdminAccountsRolesRoute
  '/admin/accounts': typeof AdminAccountsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/campuses': typeof AdminCampusesRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/faculties': typeof AdminFacultiesRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/periods': typeof AdminPeriodsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/errors/404': typeof Errors404Route
  '/errors/offline': typeof ErrorsOfflineRoute
  '/instructor/class-roster': typeof InstructorClassRosterRoute
  '/instructor/course-detail': typeof InstructorCourseDetailRoute
  '/instructor/create-request': typeof InstructorCreateRequestRoute
  '/instructor/grade-history': typeof InstructorGradeHistoryRoute
  '/instructor/my-courses': typeof InstructorMyCoursesRoute
  '/instructor/my-requests': typeof InstructorMyRequestsRoute
  '/instructor/profile': typeof InstructorProfileRoute
  '/instructor/record-grades': typeof InstructorRecordGradesRoute
  '/student/academic-history': typeof StudentAcademicHistoryRoute
  '/student/available-courses': typeof StudentAvailableCoursesRoute
  '/student/create-request': typeof StudentCreateRequestRoute
  '/student/enrollment': typeof StudentEnrollmentRoute
  '/student/my-enrollments': typeof StudentMyEnrollmentsRoute
  '/student/my-grades': typeof StudentMyGradesRoute
  '/student/my-requests': typeof StudentMyRequestsRoute
  '/student/profile': typeof StudentProfileRoute
  '/admin': typeof AdminIndexRoute
  '/instructor': typeof InstructorIndexRoute
  '/registry': typeof RegistryIndexRoute
  '/student': typeof StudentIndexRoute
  '/admin/accounts/roles': typeof AdminAccountsRolesRoute
  '/admin/accounts': typeof AdminAccountsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/campuses': typeof AdminCampusesRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/faculties': typeof AdminFacultiesRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/periods': typeof AdminPeriodsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/errors/404': typeof Errors404Route
  '/errors/offline': typeof ErrorsOfflineRoute
  '/instructor/class-roster': typeof InstructorClassRosterRoute
  '/instructor/course-detail': typeof InstructorCourseDetailRoute
  '/instructor/create-request': typeof InstructorCreateRequestRoute
  '/instructor/grade-history': typeof InstructorGradeHistoryRoute
  '/instructor/my-courses': typeof InstructorMyCoursesRoute
  '/instructor/my-requests': typeof InstructorMyRequestsRoute
  '/instructor/profile': typeof InstructorProfileRoute
  '/instructor/record-grades': typeof InstructorRecordGradesRoute
  '/student/academic-history': typeof StudentAcademicHistoryRoute
  '/student/available-courses': typeof StudentAvailableCoursesRoute
  '/student/create-request': typeof StudentCreateRequestRoute
  '/student/enrollment': typeof StudentEnrollmentRoute
  '/student/my-enrollments': typeof StudentMyEnrollmentsRoute
  '/student/my-grades': typeof StudentMyGradesRoute
  '/student/my-requests': typeof StudentMyRequestsRoute
  '/student/profile': typeof StudentProfileRoute
  '/admin/': typeof AdminIndexRoute
  '/instructor/': typeof InstructorIndexRoute
  '/registry/': typeof RegistryIndexRoute
  '/student/': typeof StudentIndexRoute
  '/admin/accounts/roles': typeof AdminAccountsRolesRoute
  '/admin/accounts/': typeof AdminAccountsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/campuses'
    | '/admin/config'
    | '/admin/courses'
    | '/admin/faculties'
    | '/admin/logs'
    | '/admin/periods'
    | '/auth/login'
    | '/auth/logout'
    | '/errors/404'
    | '/errors/offline'
    | '/instructor/class-roster'
    | '/instructor/course-detail'
    | '/instructor/create-request'
    | '/instructor/grade-history'
    | '/instructor/my-courses'
    | '/instructor/my-requests'
    | '/instructor/profile'
    | '/instructor/record-grades'
    | '/student/academic-history'
    | '/student/available-courses'
    | '/student/create-request'
    | '/student/enrollment'
    | '/student/my-enrollments'
    | '/student/my-grades'
    | '/student/my-requests'
    | '/student/profile'
    | '/admin'
    | '/instructor'
    | '/registry'
    | '/student'
    | '/admin/accounts/roles'
    | '/admin/accounts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/campuses'
    | '/admin/config'
    | '/admin/courses'
    | '/admin/faculties'
    | '/admin/logs'
    | '/admin/periods'
    | '/auth/login'
    | '/auth/logout'
    | '/errors/404'
    | '/errors/offline'
    | '/instructor/class-roster'
    | '/instructor/course-detail'
    | '/instructor/create-request'
    | '/instructor/grade-history'
    | '/instructor/my-courses'
    | '/instructor/my-requests'
    | '/instructor/profile'
    | '/instructor/record-grades'
    | '/student/academic-history'
    | '/student/available-courses'
    | '/student/create-request'
    | '/student/enrollment'
    | '/student/my-enrollments'
    | '/student/my-grades'
    | '/student/my-requests'
    | '/student/profile'
    | '/admin'
    | '/instructor'
    | '/registry'
    | '/student'
    | '/admin/accounts/roles'
    | '/admin/accounts'
  id:
    | '__root__'
    | '/'
    | '/admin/campuses'
    | '/admin/config'
    | '/admin/courses'
    | '/admin/faculties'
    | '/admin/logs'
    | '/admin/periods'
    | '/auth/login'
    | '/auth/logout'
    | '/errors/404'
    | '/errors/offline'
    | '/instructor/class-roster'
    | '/instructor/course-detail'
    | '/instructor/create-request'
    | '/instructor/grade-history'
    | '/instructor/my-courses'
    | '/instructor/my-requests'
    | '/instructor/profile'
    | '/instructor/record-grades'
    | '/student/academic-history'
    | '/student/available-courses'
    | '/student/create-request'
    | '/student/enrollment'
    | '/student/my-enrollments'
    | '/student/my-grades'
    | '/student/my-requests'
    | '/student/profile'
    | '/admin/'
    | '/instructor/'
    | '/registry/'
    | '/student/'
    | '/admin/accounts/roles'
    | '/admin/accounts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminCampusesRoute: typeof AdminCampusesRoute
  AdminConfigRoute: typeof AdminConfigRoute
  AdminCoursesRoute: typeof AdminCoursesRoute
  AdminFacultiesRoute: typeof AdminFacultiesRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminPeriodsRoute: typeof AdminPeriodsRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthLogoutRoute: typeof AuthLogoutRoute
  Errors404Route: typeof Errors404Route
  ErrorsOfflineRoute: typeof ErrorsOfflineRoute
  InstructorClassRosterRoute: typeof InstructorClassRosterRoute
  InstructorCourseDetailRoute: typeof InstructorCourseDetailRoute
  InstructorCreateRequestRoute: typeof InstructorCreateRequestRoute
  InstructorGradeHistoryRoute: typeof InstructorGradeHistoryRoute
  InstructorMyCoursesRoute: typeof InstructorMyCoursesRoute
  InstructorMyRequestsRoute: typeof InstructorMyRequestsRoute
  InstructorProfileRoute: typeof InstructorProfileRoute
  InstructorRecordGradesRoute: typeof InstructorRecordGradesRoute
  StudentAcademicHistoryRoute: typeof StudentAcademicHistoryRoute
  StudentAvailableCoursesRoute: typeof StudentAvailableCoursesRoute
  StudentCreateRequestRoute: typeof StudentCreateRequestRoute
  StudentEnrollmentRoute: typeof StudentEnrollmentRoute
  StudentMyEnrollmentsRoute: typeof StudentMyEnrollmentsRoute
  StudentMyGradesRoute: typeof StudentMyGradesRoute
  StudentMyRequestsRoute: typeof StudentMyRequestsRoute
  StudentProfileRoute: typeof StudentProfileRoute
  AdminIndexRoute: typeof AdminIndexRoute
  InstructorIndexRoute: typeof InstructorIndexRoute
  RegistryIndexRoute: typeof RegistryIndexRoute
  StudentIndexRoute: typeof StudentIndexRoute
  AdminAccountsRolesRoute: typeof AdminAccountsRolesRoute
  AdminAccountsIndexRoute: typeof AdminAccountsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/': {
      id: '/student/'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registry/': {
      id: '/registry/'
      path: '/registry'
      fullPath: '/registry'
      preLoaderRoute: typeof RegistryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor/': {
      id: '/instructor/'
      path: '/instructor'
      fullPath: '/instructor'
      preLoaderRoute: typeof InstructorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/profile': {
      id: '/student/profile'
      path: '/student/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/my-requests': {
      id: '/student/my-requests'
      path: '/student/my-requests'
      fullPath: '/student/my-requests'
      preLoaderRoute: typeof StudentMyRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/my-grades': {
      id: '/student/my-grades'
      path: '/student/my-grades'
      fullPath: '/student/my-grades'
      preLoaderRoute: typeof StudentMyGradesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/my-enrollments': {
      id: '/student/my-enrollments'
      path: '/student/my-enrollments'
      fullPath: '/student/my-enrollments'
      preLoaderRoute: typeof StudentMyEnrollmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/enrollment': {
      id: '/student/enrollment'
      path: '/student/enrollment'
      fullPath: '/student/enrollment'
      preLoaderRoute: typeof StudentEnrollmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/create-request': {
      id: '/student/create-request'
      path: '/student/create-request'
      fullPath: '/student/create-request'
      preLoaderRoute: typeof StudentCreateRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/available-courses': {
      id: '/student/available-courses'
      path: '/student/available-courses'
      fullPath: '/student/available-courses'
      preLoaderRoute: typeof StudentAvailableCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/academic-history': {
      id: '/student/academic-history'
      path: '/student/academic-history'
      fullPath: '/student/academic-history'
      preLoaderRoute: typeof StudentAcademicHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor/record-grades': {
      id: '/instructor/record-grades'
      path: '/instructor/record-grades'
      fullPath: '/instructor/record-grades'
      preLoaderRoute: typeof InstructorRecordGradesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor/profile': {
      id: '/instructor/profile'
      path: '/instructor/profile'
      fullPath: '/instructor/profile'
      preLoaderRoute: typeof InstructorProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor/my-requests': {
      id: '/instructor/my-requests'
      path: '/instructor/my-requests'
      fullPath: '/instructor/my-requests'
      preLoaderRoute: typeof InstructorMyRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor/my-courses': {
      id: '/instructor/my-courses'
      path: '/instructor/my-courses'
      fullPath: '/instructor/my-courses'
      preLoaderRoute: typeof InstructorMyCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor/grade-history': {
      id: '/instructor/grade-history'
      path: '/instructor/grade-history'
      fullPath: '/instructor/grade-history'
      preLoaderRoute: typeof InstructorGradeHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor/create-request': {
      id: '/instructor/create-request'
      path: '/instructor/create-request'
      fullPath: '/instructor/create-request'
      preLoaderRoute: typeof InstructorCreateRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor/course-detail': {
      id: '/instructor/course-detail'
      path: '/instructor/course-detail'
      fullPath: '/instructor/course-detail'
      preLoaderRoute: typeof InstructorCourseDetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor/class-roster': {
      id: '/instructor/class-roster'
      path: '/instructor/class-roster'
      fullPath: '/instructor/class-roster'
      preLoaderRoute: typeof InstructorClassRosterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/errors/offline': {
      id: '/errors/offline'
      path: '/errors/offline'
      fullPath: '/errors/offline'
      preLoaderRoute: typeof ErrorsOfflineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/errors/404': {
      id: '/errors/404'
      path: '/errors/404'
      fullPath: '/errors/404'
      preLoaderRoute: typeof Errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/logout': {
      id: '/auth/logout'
      path: '/auth/logout'
      fullPath: '/auth/logout'
      preLoaderRoute: typeof AuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/periods': {
      id: '/admin/periods'
      path: '/admin/periods'
      fullPath: '/admin/periods'
      preLoaderRoute: typeof AdminPeriodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/admin/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/faculties': {
      id: '/admin/faculties'
      path: '/admin/faculties'
      fullPath: '/admin/faculties'
      preLoaderRoute: typeof AdminFacultiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/courses': {
      id: '/admin/courses'
      path: '/admin/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AdminCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/config': {
      id: '/admin/config'
      path: '/admin/config'
      fullPath: '/admin/config'
      preLoaderRoute: typeof AdminConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/campuses': {
      id: '/admin/campuses'
      path: '/admin/campuses'
      fullPath: '/admin/campuses'
      preLoaderRoute: typeof AdminCampusesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/accounts/': {
      id: '/admin/accounts/'
      path: '/admin/accounts'
      fullPath: '/admin/accounts'
      preLoaderRoute: typeof AdminAccountsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/accounts/roles': {
      id: '/admin/accounts/roles'
      path: '/admin/accounts/roles'
      fullPath: '/admin/accounts/roles'
      preLoaderRoute: typeof AdminAccountsRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminCampusesRoute: AdminCampusesRoute,
  AdminConfigRoute: AdminConfigRoute,
  AdminCoursesRoute: AdminCoursesRoute,
  AdminFacultiesRoute: AdminFacultiesRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminPeriodsRoute: AdminPeriodsRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthLogoutRoute: AuthLogoutRoute,
  Errors404Route: Errors404Route,
  ErrorsOfflineRoute: ErrorsOfflineRoute,
  InstructorClassRosterRoute: InstructorClassRosterRoute,
  InstructorCourseDetailRoute: InstructorCourseDetailRoute,
  InstructorCreateRequestRoute: InstructorCreateRequestRoute,
  InstructorGradeHistoryRoute: InstructorGradeHistoryRoute,
  InstructorMyCoursesRoute: InstructorMyCoursesRoute,
  InstructorMyRequestsRoute: InstructorMyRequestsRoute,
  InstructorProfileRoute: InstructorProfileRoute,
  InstructorRecordGradesRoute: InstructorRecordGradesRoute,
  StudentAcademicHistoryRoute: StudentAcademicHistoryRoute,
  StudentAvailableCoursesRoute: StudentAvailableCoursesRoute,
  StudentCreateRequestRoute: StudentCreateRequestRoute,
  StudentEnrollmentRoute: StudentEnrollmentRoute,
  StudentMyEnrollmentsRoute: StudentMyEnrollmentsRoute,
  StudentMyGradesRoute: StudentMyGradesRoute,
  StudentMyRequestsRoute: StudentMyRequestsRoute,
  StudentProfileRoute: StudentProfileRoute,
  AdminIndexRoute: AdminIndexRoute,
  InstructorIndexRoute: InstructorIndexRoute,
  RegistryIndexRoute: RegistryIndexRoute,
  StudentIndexRoute: StudentIndexRoute,
  AdminAccountsRolesRoute: AdminAccountsRolesRoute,
  AdminAccountsIndexRoute: AdminAccountsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
